"use strict";

var fs = require("fs");
var eventsDir = __dirname + "/events";
var eventFiles = fs.readdirSync(eventsDir);
var events = [];
var tags = [];
var days = [];

function registerTags(tagsToAdd) {
  if (tagsToAdd) {
    tags = [...new Set([...tags ,...tagsToAdd])];
  }
}


var tagsToRemove = [
  "Annat",
  "Ansvar",
  "Arbetskraftsbrist",
  "Arbetslivsmuseum",
  "Assistansersättning",
  "BEPS",
  "Barnrätt",
  "Bemötande",
  "Bil",
  "Bostäder",
  "Brott",
  "Bränslen",
  "Bygga broar",
  "Byggregler",
  "Chef",
  "Cirkulär ekonomi",
  "Colombia",
  "Autonomous",
  "Arbetsmarknadsinriktad rehabilitering",
  "Affärsmässig samhällsnytta",
  "Affärsmöjligheter",
  "Anhörig",
  "Betyg",
  "Bränsle",
  "Debatt",
  "Dialog",
  "Drivmedel",
  "Elit",
  "Etablering",
  "Flygskatt",
  "Folk",
  "Framtid",
  "Förebyggande",
  "Förmaksflimmer",
  "Förnybart",
  "Förpackningar",
  "Förändring",
  "Global",
  "Hemmasittare",
  "Humaniora",
  "Hälsoekonomiskt",
  "Högflourerande ämnen",
  "Idéburen",
  "Integritet",
  "Partiets dag",
  "Partiledare",
  "PFAS",
  "Politik",
  "Politiker",
  "Medborgare",
  "Könsstympning",
  "Kött",
  "LSS",
  "Laddbara fordon",
  "Lagstiftning",
  "Landsting",
  "Kommunalt monopol",
  "Kontanter",
  "Konvertit",
  "Koordinering",
  "Kosmetika",
  "Kostnadsutveckling",
  "Kristdemokraterna",
  "Kryssning",
  "Kränkningar",
  "Likvärdighet",
  "Logopeder",
  "Matchningsproblematik",
  "Mindfulness",
  "Mjukvara",
  "Musik",
  "Miljonprogram",
  "Myndigheter",
  "Osteoporos",
  "Paradigmskifte",
  "Patientorganisation",
  "Penningreform",
  "Påverkan",
  "Reduktionsplikt",
  "Reell kompetens",
  "Regelverk",
  "Regeringen",
  "Nevroledarskap",
  "NoNetLoss",
  "Nya svenskar",
  "Nyanlända",
  "Offentlig säljverksamhet",
  "Omställning",
  "Organskörd",
  "Resolution 2250",
  "Reseavdrag",
  "Representativitet",
  "Resor",
  "Resurstilldelning",
  "Reumatism",
  "Revision",
  "Robot",
  "Rädsla påverkar",
  "Rättvisa",
  "Samskapande",
  "Samtal",
  "Samverkan",
  "Samverkande myndigheter",
  "Samvetsfångar",
  "Sexuella övergrepp",
  "Sexuella trakasserier",
  "Seyfo",
  "Testbädd",
  "TMK-17",
  "Tal",
  "Tillit",
  "Tillit förändrar",
  "Tillitsbyggande",
  "Tillitsdelegationen",
  "Tillstånd",
  "Trump",
  "Trähus",
  "Tvångsarbete",
  "Unga Vuxna",
  "Tvångsarbete",
  "Utsläpp",
  "Utveckling",
  "Validering",
  "Vattenförvaltning",
  "Vinstdrivande företag",
  "Välfärdsföretag",
  "Välgörenhet",
  "Vätgas",
  "Yrkeskategorier",
  "Yrkesutbildning",
  "innovationspartnerskap",
  "Öppenhet",
  "Subvention",
  "Syrianer",
  "Solel",
  "Social investering",
  "Sjuksköterska",
  "Sjukvårdsförsäkring",
  "Statligt huvudmannaskap",
  "Stillasittande",
  "Stresshantering",
  "Stroke",
  "Studenter",
  "Styrmedel",
  "Styrning",
  "Styrsystem",
  "Centerpartiet",
  "Benskörhet",
  "Djur",
  "Ekologisk kompensation",
  "Elektrifiering",
  "Europaparlamentet",
  "FN",
  "Folkbildning",
  "Folkmord",
  "Foodtech",
  "Fossilfri transportsektor",
  "Föräldraförsäkring",
  "Grannsamverkan",
  "Grundvatten",
  "Gruvor",
  "Hat",
  "Hot",
  "Humanitära kriser",
  "Avtalsrörelsen",
  "Avspänning",
  "Bedrägeri",
  "Bilism",
  "Bioekonomi",
  "Biologisk mångfald",
  "Blockpolitik",
  "Brottsutvecklingen",
  "Design",
  "Diagnostik",
  "Elevhälsa",
  "Etik",
  "Finansiering",
  "Fossilfritt",
  "Israel",
  "Palestina",
  "Kemikalier",
  "Kommunikation",
  "Källkritik",
  "Life Science",
  "Lån",
  "Löner",
  "Löneskillnader",
  "Medkänsla",
  "Mellanöstern",
  "OECD",
  "Ohälsa",
  "Otrygghet",
  "Personlig assistans",
  "Ryssland",
  "Sjukskrivning",
  "Självmord",
  "Skuldsättning",
  "Social innovation",
  "Sponsring",
  "Språkstörning",
  "Statistik",
  "Sverigebilden",
  "Teater",
  "Kyrka",
  "Tolkning",
  "Verksamhetsstyrning",
  "Vårdnadstvist",
  "konflikthantering",
  "Allas lika värde",
  "Agenda 2030",
  "1177",
  "2030",
  "3D",
  "A-kassa",
  "ADHD",
  "Abort",
  "Alkoholfri",
  "AmCham",
  "Anställningsbarhet",
  "Antibiotikaresistens",
  "Arbetslöshetsförsäkring",
  "Universell tillgänglighet",
  "Urban norm",
  "Utgivare",
  "VR",
  "Vaccination",
  "Val 2018",
  "Varumärkeskommunikation",
  "Viltförvaltning",
  "Vinproduktion",
  "Visualisering",
  "Vägslitageavgift",
  "Vänsterpartiet",
  "Värdmoderskap",
  "Vårdresultat",
  "Yrkesintroduktion",
  "allmän värnplikt",
  "demens",
  "idéburet offentligt partnerskap",
  "medtech",
  "morgondagens vård",
  "vårdkedja",
  "Ätstörning",
  "Åldergräns",
  "Åldergräns på nätet",
  "Återanvändning",
  "Återfall i brott",
  "Återvinningsbara förpackningar",
  "ÖB",
  "Överbefälhavare",
  "Arbetsgivarorganisation",
  "Läsning",
  "Medborgardialog",
  "Mentorskap",
  "Min stora dag",
  "Mobilitet",
  "Motivation",
  "Multikanal",
  "Naturturism",
  "Nudging",
  "Nyindustrialiseringsstrategi",
  "Nära-nollenergibyggnader",
  "Obligatorisk ventilations kontroll",
  "Offentlighetsprincipen",
  "Planetens gränser",
  "Podcast",
  "Policy",
  "Producentansvar",
  "Psykiatriregister",
  "Riskförebyggande åtgärder",
  "Risktagande",
  "Shrinking space",
  "Själavård",
  "Sjömat",
  "Skräp",
  "Social Impact Bond",
  "Stad–land konflikt",
  "Strejkrätten",
  "Styrelsekompetenser",
  "Surrogatmoderskap",
  "Surrogatmödraskap",
  "Sustainable business",
  "Svenska Modellen",
  "Sverigedemokraterna",
  "Sverigeförhandlingen",
  "Sveriges Bussföretag",
  "Systemkollaps",
  "Techbolag",
  "Termitventilation",
  "Tjänstesektorn",
  "Transhumanism",
  "Underbara ADHD",
  "Undernäring",
  "Ursprungsfolk",
  "Sanningsanspråk",
  "Skolledare",
  "Snabbspår",
  "Stadsmiljöavtal",
  "Staten",
  "Säkerhetskameror",
  "Talanghantering",
  "Talmannen",
  "Tidiga insatser",
  "Transportplanering",
  "Vinst i välfärden",
  "Alliansen",
  "Analys",
  "Argumentation",
  "Avfallsförbränning",
  "Elvägar",
  "Expertis",
  "Fiktion",
  "Fintech",
  "Flexibilitet",
  "Gagrule",
  "Gröna obligationer",
  "Havsmiljödirektivet",
  "Hopp",
  "Hälsolitteracitet",
  "Neuropsykiatriska funktionsnedsättningar",
  "Ny lag",
  "Nya regler",
  "Nyanlända akademiker",
  "Offentliga rummet",
  "Olikheter",
  "Omsorgskvarter",
  "Oregonmodellen",
  "Organturism",
  "Ostlänken",
  "PISA",
  "PR-branschen",
  "Parallella samhällen",
  "Patent",
  "Prevention",
  "Retorik",
  "Rörelse",
  "SRHR",
  "Satir",
  "Servicenivå",
  "Skatteflykt",
  "Socialt arbete",
  "Sorg",
  "Tullen",
  "Växtbaserad",
  "Assyrier",
  "Big data",
  "Bokrasch",
  "Bonus–malus",
  "Cancerrehabilitering",
  "Dagsljus",
  "Deltidsbrandkår",
  "E-krona",
  "Ekologisk hållbarhet",
  "Ekologiska fotavtryck",
  "Faktaresistens",
  "Fertilitet",
  "Förbättra världen",
  "Författare",
  "Förtroendevald",
  "Förvärvad hjärnskada",
  "Hästunderstödd terapi",
  "IBS",
  "ID-kapning",
  "Independent Living",
  "Insuretech",
  "KOL",
  "Kality",
  "Karriärister",
  "Kilometerskatt",
  "Kinas kommunistparti",
  "Kommunallagen",
  "Konfliktmineraler",
  "Kooperativ",
  "Kropp",
  "LAS",
  "LED-belysning",
  "Labb",
  "Leveranssäkerhet",
  "Lotteri",
  "Multipel skleros",
  "Människosyn",
  "Möten",
  "Patientperspektiv",
  "Pånyttfödelse",
  "Renovering",
  "Roman",
  "Samhällsdebatt",
  "Screening",
  "Språkrör",
  "Transformation",
  "Trygghetsboende",
  "Värderingar",
  "Affärsetik",
  "Apotek",
  "Arbetsgivare",
  "Arbetstider",
  "Arbetstillstånd",
  "Arbetsträning",
  "Arkeologi",
  "Avkastning",
  "Behandling",
  "Beroendebeteende",
  "Beteendeförändring",
  "Biobanker",
  "civilsamhälle",
  "Våldtäkt",
  "Valfrihet",
  "Värmelösingar",
  "Växtförädling",
  "Trygghet",
  "Utrikeshandel",
  "Utbildningssystem",
  "Unga makthavare",
  "Transparens",
  "Tandvård",
  "Blockkedjan",
  "Branschstandarder",
  "Desinformation",
  "Doktorand",
  "Dövblindhet",
  "EU Horizon2020",
  "Empati",
  "Existentiell hälsa",
  "Familjecentral",
  "Finansminister",
  "Generationskrock",
  "Global konkurrens",
  "Gränshinder",
  "Human rights defenders",
  "Hästunderstödd pedagogik",
  "Icke smittsamma sjukdomar",
  "Industriell symbios",
  "Installationsbranschen",
  "Invånare",
  "Jämställdhet i förorterna",
  "Karriärväxling",
  "Megaregion",
  "Motstånd",
  "Mottagande",
  "NPF",
  "Samtrafiken",
  "Sexualundervisning",
  "Styrelse",
  "Stöld"
];

var tagsMergeMappings = {
  "Civila samhället": "Civilsamhället",
  "Byggande": "Bostadsbyggande",
  "Cyberhot": "Dataskydd",
  "Djurskydd": "Djurrätt",
  "Digital hälsa": "E-hälsa",
  "EU-kommissionen": "EU",
  "Ekonomiska styrmedel": "Ekonomi",
  "El": "Energi",
  "Fake news": "Falska nyheter",
  "Fastighetsbranschen": "Bostadsbyggande",
  "Investeringar": "Finans",
  "Fonder": "Finans",
  "Ungdomar": "Barn och ungdomar",
  "Barn/ungdom": "Barn och ungdomar",
  "Barn": "Barn och ungdomar",
  "Barnäktenskap": ["Barn och ungdomar", "Barns rättigheter"],
  "Flickors rättigheter": ["Barn och ungdomar", "Barns rättigheter"],
  "Flyktingar": "Flyktingpolitik",
  "Flyktingmottagande": "Flyktingpolitik",
  "Energilösningar": "Energi",
  "Företagsutveckling": "Företag",
  "Forskning": "Forskning och innovation",
  "Forskning och utbildning": ["Forskning och innovation", "Utbilding"],
  "Funktionsrätt": "Funktionsnedsättning",
  "Företag": "Företagande",
  "Grundskola": "Skola",
  "Friskola": "Skola",
  "Gymnasieskola": "Skola",
  "Hyrläkare": "Vård och omsorg",
  "Hållbarhet": "Klimat/miljö",
  "Hållbar investering": "Klimat/miljö",
  "Hållbar konsumtion": "Klimat/miljö",
  "Hållbar livsstil": "Klimat/miljö",
  "Hållbar matkonsumtion": "Klimat/miljö",
  "Hållbar stadsutveckling": ["Klimat/miljö", "Stadsutveckling"],
  "Hållbar utveckling": "Klimat/miljö",
  "Hållbarhetsmål": "Klimat/miljö",
  "Hållbart samhälle": "Klimat/miljö",
  "Hållbart samhällsbyggande": "Klimat/miljö",
  "Hållbar produktion": "Klimat/miljö",
  "Hållbar upphandling": "Klimat/miljö",
  "Hållbar välfärd": "Klimat/miljö",
  "Hållbara affärstillfällen": "Klimat/miljö",
  "Hållbara investeringar": "Klimat/miljö",
  "Hållbara transporter": "Klimat/miljö",
  "Hållbart byggande": "Klimat/miljö",
  "Hållbart drivmedel": "Klimat/miljö",
  "Högskola": "Högre utbildning",
  "Universitet": "Högre utbildning",
  "Hyressättning": "Bostadspolitik",
  "Innovationssystem": "Innovation",
  "Integration": "Integration/mångfald",
  "Jämlik vård": ["Jämlikhet", "Vård"],
  "Kretslopp": "Klimat/miljö",
  "Kretsloppsliknande system": "Klimat/miljö",
  "Återvinning": "Klimat/miljö",
  "Klimat": "Klimat/miljö",
  "Klimatanpassning": "Klimat/miljö",
  "Klimatmål": "Klimat/miljö",
  "Klimatpolitik": "Klimat/miljö",
  "Klimatpolitikens 2030-mål": "Klimat/miljö",
  "Klimatpolitiska transportmål": ["Klimat/miljö", "Transport"],
  "Klimatsmart": "Klimat/miljö",
  "Miljö": "Klimat/miljö",
  "Miljögifter": "Klimat/miljö",
  "Miljömålsberedning": "Klimat/miljö",
  "PPM": "Pension",
  "Pensionsgruppen": "Pension",
  "Premiepension": "Pension",
  "Tjänstepension": "Pension",
  "Vård": "Vård och omsorg",
  "Primärvård": "Vård och omsorg",
  "Vårdföretag": "Vård och omsorg",
  "Sjukvård": "Vård och omsorg",
  "Hälso- och sjukvård": "Vård och omsorg",
  "Hälsa": "Vård och omsorg",
  "Rehabilitering": "Vård och omsorg",
  "Cannabis": "Missbruk",
  "Narkotika": "Missbruk",
  "Lärare": "Läraryrket",
  "Mathantverk": "Mat",
  "Matkultur": "Mat",
  "Media": "Media/journalistik",
  "Medieutredningen": "Media/journalistik",
  "Medier": "Media/journalistik",
  "Kulturarv": "Kultur",
  "Utbildningspolitik": "Utbildning",
  "Kunskapsmål": "Utbildning",
  "Kvinnofrid": "Våld",
  "Liberalism": "Ideologi",
  "Kompetensbrist": "Kompetens",
  "Kompetensförsörjning": "Kompetens",
  "Konkurrenskraft": "Konkurrens",
  "Konsumenter": "Konsumtion",
  "Konsumtionens klimatpåverkan": ["Konsumtion", "Klimat/miljö"],
  "Nazism": "Extremism",
  "Regionfrågor": "Regional utveckling",
  "Religionsfrihet": ["Religion", "Mänskliga rättigheter"],
  "Rättsväsende": "Rättsväsende/brott",
  "Samhällsanalyser": "Samhälle",
  "Samhällsbyggande": "Samhälle",
  "Samhällsekonomi": "Samhälle",
  "Samhällsnytta": "Samhälle",
  "Samhällsutveckling": "Samhälle",
  "Transport": "Transporter",
  "Transportekonomi": "Transporter",
  "Våldsbejakande extremism": ["Extremism", "Våld"],
  "sänkt arbetstid": "Samhälle",
  "Sysselsättning": "Sysselsättning/arbetsmarknad",
  "Arbetsmarknadsfrågor": "Sysselsättning/arbetsmarknad",
  "Jobb": "Sysselsättning/arbetsmarknad",
  "Arbetsmarknad": "Sysselsättning/arbetsmarknad",
  "Stadspolitik": "Stadsutveckling",
  "Specialpedagogik": "Pedagogik",
  "Småföretag": "Småföretagande",
  "Småföretagare": "Småföretagande",
  "Skolutveckling": "Skola",
  "Skolpolitik": "Skola",
  "Skogsbruk": "Skog",
  "Bildning": "Utbildning",
  "Akademi": "Forskning och innovation",
  "Alkohol": "Missbruk",
  "Djurförsök": "Djurrätt",
  "Energifattigdom": "Energi",
  "Energieffektivisering": "Energi",
  "Enkla jobb": "Sysselsättning/arbetsmarknad",
  "Fritt skolval": "Skola",
  "Företag": "Företagande",
  "Förort": "Bostadsbyggande",
  "Föräldrastöd": "Föräldrar",
  "GDPR": "Dataskydd",
  "Barnkonventionen": ["Barn och ungdomar", "Barns rättigheter"],
  "Folksjukdomar": "Folkhälsa",
  "Islamism": "Extremism",
  "Fred": "Fred och Konflikt",
  "Konflikt": "Fred och Konflikt",
  "Konfliktlösning": "Fred och Konflikt",
  "Mutor": "Korruption",
  "Sparande": "Ekonomi",
  "Försvarspolitik": "Säkerhet och Försvar",
  "Säkerhet": "Säkerhet och Försvar",
  "Säkerhet/försvar": "Säkerhet och Försvar",
  "Säkerhetspolitik": "Säkerhet och Försvar",
  "Teologi": "Religion",
  "Tobak": "Folkhälsa",
  "Urbanisering": "Bostadspolitik",
  "Vårdförlopp": "Vård och omsorg",
  "Vårdkvalitet": "Vård och omsorg",
  "Äldre": "Vård och omsorg",
  "Äldreboende": "Vård och omsorg",
  "Äldreomsorg": "Vård och omsorg",
  "Välfärdsteknologi": "Välfärd",
  "Välfärdstjänster": "Välfärd",
  "Välfärdsuppdraget": "Välfärd",
  "Välfärdsutveckling": "Välfärd",
  "Vuxenutbildning": "Utbildning",
  "Vegan": "Vegetarianism",
  "Vegansk": "Vegetarianism",
  "Vegetarisk": "Vegetarianism",
  "Vego": "Vegetarianism",
  "Vattenbrist": "Vattentillgång",
  "Vattendirektivet": "Vattentillgång",
  "Vattenkvalité": "Vattentillgång",
  "Afrofobi": "Rasism",
  "Antifacism": "Rasism",
  "Antirasism": "Rasism",
  "Rasismforskning": "Rasism",
  "Elhandelsbolag": "Energi",
  "Elkund": "Energi",
  "Elmarknad": "Energi",
  "Elnät": "Energi",
  "Elproduktion": "Energi",
  "Elvägar": "Energi",
  "Energilager": "Energi",
  "Energiskatt": "Energi",
  "Energisystem": "Energi",
  "Gagrule": "Energi",
  "Gröna obligationer": "Energi",
  "Havsmiljödirektivet": "Energi",
  "Hopp": "Energi",
  "Hälsolitteracitet": "Energi",
  "Medicinsk kvalitet": "Medecin",
  "Medicinteknik": "Medecin",
  "Medieetik": "Media/journalistik",
  "Massmedia": "Media/journalistik",
  "Medieträning": "Media/journalistik",
  "Undersökande journalistik": "Media/journalistik",
  "Allmännyttan": "Bostadspolitik",
  "Alternativa fakta": "Falska nyheter",
  "Arbetsförmedlingen": "Sysselsättning/arbetsmarknad",
  "Arbetskraft": "Sysselsättning/arbetsmarknad",
  "Arbetsmarknadskunskap": "Sysselsättning/arbetsmarknad",
  "Ungdomars levnadsvillkor": "Barn och ungdomar",
  "Terrorhot": "Terrorism",
  "Biodrivmedel": "Klimat/miljö",
  "Bioenergi": "Klimat/miljö",
  "Biologisk vattenrening": "Klimat/miljö",
  "Bioteknik": "Klimat/miljö",
  "Blå tillväxt": "Klimat/miljö",
  "Fossilfria transporter": "Klimat/miljö",
  "Fossiloberoende": "Klimat/miljö",
  "Förnybar Energi": "Klimat/miljö",
  "Globala målen": "Klimat/miljö",
  "Källsortering": "Klimat/miljö",
  "Matsvinn": "Klimat/miljö",
  "Mikroplast": "Klimat/miljö",
  "Miljömärkning": "Klimat/miljö",
  "Miljönytta": "Klimat/miljö",
  "Miljöpolitik": "Klimat/miljö",
  "Miljörisker": "Klimat/miljö",
  "Miljörörelse": "Klimat/miljö",
  "Mänsklig hållbarhet": "Klimat/miljö",
  "Naturresurser": "Klimat/miljö",
  "Nedskräpning": "Klimat/miljö",
  "Parisavtal": "Klimat/miljö",
  "Plast": "Klimat/miljö",
  "Regnskog": "Klimat/miljö"
};

function cleanTags(tags) {
  tags = tags.filter(function(tag) {
    return tagsToRemove.indexOf(tag) < 0;
  });

  var newTags = [];
  tags = tags.map(function(tag) {
    if (tagsMergeMappings[tag]) {
      if (Array.isArray(tagsMergeMappings[tag])) {
        newTags.concat(tagsMergeMappings[tag]);
        return tagsMergeMappings[tag][0];
      } else {
        return tagsMergeMappings[tag];
      }
    } else {
      return tag;
    }
  });

  return [...new Set([...tags ,...newTags])];
}

function registerDays(timesToAdd) {
  var daysToAdd = [];
  if (timesToAdd) {
    timesToAdd.forEach(function(time) {
      var date = new Date(time.start);
      var y = date.getUTCFullYear();
      var m = date.getUTCMonth() + 1;
      var d = date.getUTCDate();
      daysToAdd.push(y + "-" + (m < 10 ? "0" + m : m) + "-" + (d < 10 ? "0" + d : d));
    })
    days = [...new Set([...days ,...daysToAdd])];
  }
}

function registerEvent(event) {
  events.push(event);
}

for (var i = 0, l = eventFiles.length; i < l; i++) {
  var eventData = JSON.parse(fs.readFileSync(eventsDir + "/" + eventFiles[i]));

  if (!eventData.tags) { eventData.tags = []; }
  eventData.tags.push(eventData.area);
  eventData.tags = cleanTags(eventData.tags);

  if (eventData.times) {
    registerEvent(eventData);
    registerTags(eventData.tags);
    registerDays(eventData.times);
  }
}

function isSameDay(date1, date2) {
  return date1.getFullYear() === date2.getFullYear() && date1.getMonth() === date2.getMonth() && date1.getDate() === date2.getDate();
};

function filterEvents(filters) {
  var filteredEvents = [];

  if (filters.tags && filters.tags.length === 0 && filters.days && filters.days.length === 0) {
    return events;
  }

  filteredEvents = events.filter(function(event) {
    if (filters.tags && filters.tags.length > 0) {
      var matching = false;
      filters.tags.forEach(function(tag) {
        if (event.tags.indexOf(tag) >= 0) {
          matching = true;
        }
      });
      if (!matching) {
        return false;
      }
    }

    if (filters.days && filters.days.length > 0) {
      var matching = false;

      filters.days = filters.days.map(function(d) {
        return new Date(d);
      });

      filters.days.forEach(function(day) {
        var matchingDays = event.times.filter(function(time) {
          return isSameDay(new Date(time.start), day);
        });
        if (matchingDays.length > 0) {
          matching = true;
        }
      });

      if (!matching) {
        return false;
      }
    }

    return true;
  });

  return filteredEvents;
}

console.log(events.length);

module.exports = {
  events: events,
  days: days.sort(),
  tags: tags.sort().filter(function(item) {
    if (!item) { return false; }
    return item.trim() != "";
  }),
  filterEvents: filterEvents
};
